<script setup lang="ts">
import { computed, nextTick, ref, reactive, watch, watchEffect } from 'vue'
import { compile } from '@vue/compiler-dom'
import { FlaskConical, Play, RotateCcw, ArrowRight, Code2, Info, Check, Zap } from 'lucide-vue-next'
import { openSource } from '../composables/useWorkspace'
import { simulateDiff } from '../features/diff'
const tabs=[{name:'依赖收集',source:'packages/reactivity/src/dep.ts',symbol:'track'}, {name:'Computed 缓存',source:'packages/reactivity/src/computed.ts',symbol:'computed'}, {name:'调度器 / nextTick',source:'packages/runtime-core/src/scheduler.ts',symbol:'queueJob'}, {name:'Keyed Diff / LIS',source:'packages/runtime-core/src/renderer.ts',symbol:'patchKeyedChildren'}, {name:'生命周期',source:'packages/runtime-core/src/apiLifecycle.ts',symbol:'onMounted'}, {name:'模板编译',source:'packages/compiler-core/src/compile.ts',symbol:'baseCompile'}]
const tab=ref(0),step=ref(0)
const count=ref(1),other=ref(5),useCount=ref(true),depLogs=ref<string[]>([])
const log=(message:string)=>{depLogs.value=[message,...depLogs.value].slice(0,12)}
watchEffect(()=>{const current=useCount.value?'count':'other';const v=useCount.value?count.value:other.value;queueMicrotask(()=>{log(`读取/track（示意）→ ${current}`);log(`effect 执行 → 读取 ${current} = ${v}`)})}, {onTrack:e=>queueMicrotask(()=>log(`track 依赖 → ${String(e.key)}`)),onTrigger:e=>queueMicrotask(()=>log(`trigger 通知 → ${String(e.key)}`)),flush:'sync'})
const price=ref(12),amount=ref(2),computeCalls=ref(0),computedReads=ref<string[]>([])
let calculations=0
const total=computed(()=>{calculations++;return price.value*amount.value})
function readComputed(){const result=total.value;computeCalls.value=calculations;computedReads.value=[`读取 total.value → ${result}`, ...computedReads.value].slice(0,7)}
const flushCount=ref(0),flushLogs=ref<string[]>([])
watch(flushCount,()=>{flushLogs.value=[...flushLogs.value,`watch(pre) 执行，值=${flushCount.value}`]})
async function flushBatch(){flushLogs.value=[];flushLogs.value.push('同步开始');flushCount.value++;flushCount.value++;flushCount.value++;flushLogs.value.push(`连续赋值 3 次，当前状态 ${flushCount.value}`);await nextTick();flushLogs.value.push('await nextTick 之后：本轮 watch / 组件更新已结束')}
const oldList=ref('A,B,C,D'),newList=ref('B,D,A,C')
const diff=computed(()=>{try{const oldKeys=oldList.value.split(/[\s,，]+/).filter(Boolean),newKeys=newList.value.split(/[\s,，]+/).filter(Boolean);return {data:simulateDiff(oldKeys,newKeys),error:''}}catch(e){return {data:null,error:e instanceof Error?e.message:String(e)}}})
const phases=[{title:'setup',text:'创建组件实例，初始化 props/slots，调用 setup 注册钩子；此时组件自己的 DOM 尚未挂载。'},{title:'beforeMount',text:'初次渲染得到 subTree，即将进行初次 DOM patch。'},{title:'mounted',text:'宿主 DOM 完成插入后调用（或排队执行）已注册的 mounted 钩子。'},{title:'beforeUpdate',text:'响应式数据变化导致组件更新，执行新的 render 和 patch 前的相关钩子。'},{title:'updated',text:'组件 DOM patch 结束后执行 updated 钩子。'},{title:'beforeUnmount → unmounted',text:'卸载时清理组件的 effect/子树，再执行相应的卸载钩子。'}]
const template=ref('<div class="card">\n  <h2>静态标题</h2>\n  <p :class="kind">{{ message }}</p>\n</div>')
const compiled=computed(()=>{try{return {code:compile(template.value,{mode:'module'}).code,error:''}}catch(e){return {code:'',error:e instanceof Error?e.message:String(e)}}})
function selectTab(index:number){tab.value=index;step.value=0}
</script>
<template><div class="page labs-page"><div class="eyebrow"><FlaskConical :size="15"/> INTERACTIVE LAB</div><h1>把抽象机制，变成可观察的状态。</h1><p class="muted">前 3 个实验直接调用当前项目的 Vue 响应式 API，Diff 和生命周期展示教学步骤；模板编译调用 @vue/compiler-dom。实验不等同于完整运行时或性能测试。</p><div class="lab-tabs"><button v-for="(item,i) in tabs" :key="item.name" :class="{active:tab===i}" @click="selectTab(i)">{{item.name}}</button></div><section class="experiment"><div class="experiment-title"><div><small>EXPERIMENT {{String(tab+1).padStart(2,'0')}}</small><h2>{{tabs[tab]!.name}}</h2></div><button class="secondary" @click="openSource(tabs[tab]!.source,tabs[tab]!.symbol)"><Code2 :size="15"/> 对照源码</button></div>
 <template v-if="tab===0"><p class="muted">观察 effect 执行时读取的依赖，及修改数据后的 trigger。开发模式下还会显示 Vue 的 onTrack/onTrigger 真实调试事件；生产模式保留读取日志。切换分支后旧分支不再被依赖。</p><div class="lab-controls"><button @click="count++"><Zap :size="14"/> count +1（{{count}}）</button><button @click="other++">other +1（{{other}}）</button><button @click="useCount=!useCount">切换分支 → {{useCount?'count':'other'}}</button><button @click="depLogs=[]"><RotateCcw :size="14"/> 清空日志</button></div><div class="flow-chips"><span class="active">Proxy get</span><ArrowRight :size="15"/><span>track / Dep</span><ArrowRight :size="15"/><span>trigger / effect</span></div><div class="trace-list"><div v-for="(line,i) in depLogs" :key="i"><span>{{String(depLogs.length-i).padStart(2,'0')}}</span>{{line}}</div></div></template>
 <template v-else-if="tab===1"><p class="muted">computed 仅在需要时执行 getter，没有依赖变化时重复访问返回缓存。计算 getter 请保持纯函数。</p><div class="metric-grid"><div><span>单价 price</span><b>{{price}}</b><button @click="price++">+1</button></div><div><span>数量 amount</span><b>{{amount}}</b><button @click="amount++">+1</button></div><div><span>Getter 执行次数</span><b>{{computeCalls}}</b><button class="secondary" @click="readComputed">读取 total.value</button></div></div><div class="trace-list"><div v-for="(line,i) in computedReads" :key="i"><span>GET</span>{{line}}</div><div v-if="!computedReads.length" class="muted">点击「读取 total.value」开始观察。</div></div></template>
 <template v-else-if="tab===2"><p class="muted">Vue 会对同步阶段连续触发的默认 watch/组件更新做批处理；此实验的 watch 默认采用 flush: pre。</p><div class="lab-controls"><button class="primary" @click="flushBatch"><Play :size="15"/> 同步连续修改 3 次</button><button @click="flushLogs=[]"><RotateCcw :size="14"/> 清空日志</button></div><div class="flow-chips"><span class="active">同步修改</span><ArrowRight :size="15"/><span>去重调度</span><ArrowRight :size="15"/><span>微任务 flush</span><ArrowRight :size="15"/><span>nextTick</span></div><div class="trace-list"><div v-for="(line,i) in flushLogs" :key="i"><span>{{String(i+1).padStart(2,'0')}}</span>{{line}}</div><div v-if="!flushLogs.length" class="muted">点击运行观察执行顺序。</div></div></template>
 <template v-else-if="tab===3"><p class="muted">输入唯一 key，查看新节点对应的旧下标、保留的最长递增子序列（LIS）及简化移动决策。</p><div class="diff-inputs"><label>旧节点 key<input v-model="oldList" aria-label="旧节点 key"/></label><label>新节点 key<input v-model="newList" aria-label="新节点 key"/></label></div><div v-if="diff.error" class="lab-error">{{diff.error}}</div><template v-else-if="diff.data"><div class="key-sequence"><span v-for="(op,i) in diff.data.operations" :key="i" :class="op.type"><b>{{op.key}}</b><small>{{op.type==='keep'?'保留':op.type==='move'?'移动':'新建'}}</small></span></div><div class="diff-result"><div><span>新下标对应旧下标</span><code>{{diff.data.indices.join(' / ')}}</code></div><div><span>最长递增子序列保留项</span><code>{{diff.data.lis.join(', ') || '无'}}</code></div><div><span>需要删除</span><code>{{diff.data.removed.join(', ') || '无'}}</code></div></div></template><p class="hint"><Info :size="14"/> 这里分析保留与移动的教学模型。官方 patchKeyedChildren 还包含头尾同步、VNode patch、锚点与真实 DOM 操作。</p></template>
 <template v-else-if="tab===4"><p class="muted">按顺序模拟一次挂载、更新和卸载，观察钩子发生在哪个阶段。</p><div class="lifecycle-flow"><button v-for="(phase,i) in phases" :key="phase.title" :class="{current:i===step,past:i<step}" @click="step=i"><Check v-if="i<step" :size="13"/><span v-else>{{i+1}}</span>{{phase.title}}</button></div><div class="step-explain"><small>STEP {{step+1}} / {{phases.length}}</small><h3>{{phases[step]!.title}}</h3><p>{{phases[step]!.text}}</p></div><div class="lab-controls"><button :disabled="step===0" @click="step--">上一步</button><button class="primary" :disabled="step===phases.length-1" @click="step++">下一步 <ArrowRight :size="15"/></button><button @click="step=0"><RotateCcw :size="14"/> 重置</button></div></template>
 <template v-else><p class="muted">修改模板，实时查看 Vue 官方编译器生成的 render 代码，寻找 openBlock、createElementBlock、动态属性和优化提示。</p><div class="compiler-grid"><label>模板输入<textarea v-model="template" spellcheck="false" aria-label="模板输入"/></label><div><span>生成的 render 代码</span><pre v-if="!compiled.error"><code>{{compiled.code}}</code></pre><div v-else class="lab-error">{{compiled.error}}</div></div></div><p class="hint"><Info :size="14"/> 演示通过 @vue/compiler-dom 进行模板编译；单文件组件 script setup 的处理应在 compiler-sfc 中研究。</p></template>
 </section></div></template>
